server:
  port: 7777
spring:
  datasource:
    url: jdbc:mysql://bj-cynosdbmysql-grp-81mhw7ck.sql.tencentcdb.com:22837/sg_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: SDUxszx2022
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
